
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwuxjzkazytsoiruvsos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3dXhqemthenl0c29pcnV2c29zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5MjcwNzQsImV4cCI6MjA1NjUwMzA3NH0.MyCa4Qmf-Kl4ec80ZzmrdiICT_6yd2nCJpgr8uLJ9Go";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create supabase client
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
});

// Log when the client is initialized
console.log("Supabase client initialized with URL:", SUPABASE_URL);
